spring:
  application:
    name: "demo.webflux.purchase"
  output:
    ansi:
      enabled: always
  sql:
    init:
      data-locations: "classpath:sql/schema.sql"
      mode: always
  r2dbc:
    url: r2dbc:h2:file:///./purchase;DATABASE_TO_UPPER=FALSE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
logging:
  level:
    com.jpdr.apps.demo.webflux: DEBUG
app:
  base-url:
    user: ${APP_BASE_URL_USER}
    account: ${APP_BASE_URL_ACCOUNT}
    retailer: ${APP_BASE_URL_RETAILER}
    product: ${APP_BASE_URL_PRODUCT}
    stock: ${APP_BASE_URL_STOCK}
